### PR TITLE
Transitions manager

### PR DESCRIPTION
**Pull request by exomart**
Implementation of a transition manager. The idea behind it is to avoid repeating declarations/instantiation of transitions and teleporters on any scene that uses them. This is a revised and cleaner version of the code I had on my experimental branch, now replacing all the delimiters/transitions in the house scene.
-Objects that participate in the automation:
* LevelGlobals: Autoload script that finds the player actor in a scene and saves a reference, if it exists.
* TransitionsManager: Autoload script that initialices the camera manager if a player exists in the scene (uses LevelGlobals functions).
* CustomDelimiter2D: Improved version of the delimiter that automatically calculates an area (rectangle shape) that includes the area delimited by the two position nodes that form this custom scene. If the player actor enters this area TransitionsManager is called to set the camera to the new area. This delimiter has a flag visible in the editor that allows enabling or disabling this functionality so it can still be used manually.
* TwoWayTeleportNode2D: Teleport node with two endpoints (alpha/beta). Endpoints are composed of an area that detects the player (to teleport to the other endpoint), a prompt (optional) and a position node (on teleport player output). An editor flag in this node allows for instant teleport or asking for player interaction. Another editor property allows to input a fade animation time (can be 0). Uses TransitionsManager for it's functionality.

### CODE REVIEW

**Comment by exomart** [comment]
Made a change to the way this works using signals so the custom delimiter and the teleporter dont depend on the existence of the TransitionsManager.
Now I do it the other way around, the TrransitionsManager connects the teleporters/delimiters to its own functions. This means it does not necessarily have to be an autoload but could instead be created on demand (unchanged that part because its not a problem atleast for now).

**Review by starstormtwitch — COMMENTED** [review]
looks good, can you pull the most recent version of main down and merge your changes in as well as the transitions?

**Comment by exomart** [comment]
Something got fucked up with the merge, should be fixed now.

**Comment by starstormtwitch** [comment]
This has conflicts still, can you take a look and setup the transitions

**Pull request merged**
